BOWTIE2_INDEX:
 "/home/references/genomes/homo_sapiens/hg19_GRCh37/index_bowtie2/GRCh37.75"
GENOME_DATASETS:
  "/home/references/genomes/homo_sapiens/hg19_GRCh37/"
SCRIPTS:
 "/home/tempGC/Scripts"
DATASET:
 "/home/tempGC/dataset"
GENOME:
 "hg19"
PROVIRUS_SEQ:
 "AAAATCTCTAGCAGTGGCGCCCGAACAG"
LTR_SEQ:
 "GTCTGTTGTGTGACTCTGGTAAC"
ELONG_SEQ:
 "TAGAGATCCCTCAGACCCTTTTAGTCAGTGTGGAAAATCTCTA" 
LINKER_R1_SEQ:
 "AGTCCCTTAAGCGGAGCCCT"
LINKER_R2_SEQ:
 "AGGGCTCCGCTTAAGGGACT"
