REFERENCE_BASE:
  "/home/tempGC/References/"
SCRIPTS:
 "/home/tempGC/Scripts"
GENOME:
 "mm10_GRCm38"
PROVIRUS_SEQ:
 "AAAATCTCTAGCAGTGGCGCCCGAACAG"
LTR_SEQ:
 "GTCTGTTGTGTGACTCTGGTAAC"
ELONG_SEQ:
 "TAGAGATCCCTCAGACCCTTTTAGTCAGTGTGGAAAATCTCTA" 
LINKER_R1_SEQ:
 "AGTCCCTTAAGCGGAGCCCT"
LINKER_R2_SEQ:
 "AGGGCTCCGCTTAAGGGACT"
