FROM debian:latest
MAINTAINER  Guillaume Corre <gcorre@genethon.fr>
LABEL Description='this image contains bioinformatics tools to analyze Insertion sites from fragmentase pipeline' Version="1.0"
RUN apt-get update && apt-get install -y --force-yes\
	nano \
	bzip2 \
	wget \
	sudo \
	libkrb5-dev \
	libncurses5-dev \
	graphviz \
	make \
	gcc \
	g++ \
	zlib1g-dev \
	gnuplot 
	
RUN alias ll='ls -l --color=auto'
	
#### Install the bioconda repository manager
RUN wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
RUN chmod 777 /Miniconda-latest-Linux-x86_64.sh 
RUN /Miniconda-latest-Linux-x86_64.sh -b -p /opt/seqcluster/
RUN /opt/seqcluster/bin/conda install seqcluster bcbio-nextgen -c bioconda
ENV PATH /opt/seqcluster/bin:$PATH



RUN wget https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64.sh -O ./miniConda.sh
RUN chmod 777 ./miniConda.sh
RUN ./miniConda.sh -b

ENV PATH ~/miniconda3/bin:$PATH
ENV PATH /root/miniconda3/bin:$PATH
CMD echo $PATH
RUN conda install -y anaconda-client
RUN conda config --add channels r
RUN conda config --add channels conda-forge
RUN conda config --add channels bioconda


#### Bioinformatics programs: 

RUN conda install -y snakemake=3.11.2

RUN conda install -y fastqc=0.11.5

RUN conda install -y fastool=0.1.4

RUN conda install -y htslib=1.3.2

RUN conda install -y libgtextutils=0.7

RUN conda install -y bcftools=1.3.1

RUN conda install -y bedtools=2.26.0

RUN conda install -y fastx_toolkit=0.0.14

RUN conda install -y bowtie2=2.2.8

RUN conda install -y samtools=1.3.1

RUN conda install -y skewer=0.1.126

RUN conda install -y cutadapt=1.11

RUN conda install -y ea-utils=1.1.2.537

RUN conda install -y ghostscript

RUN conda install multiqc


RUN cpan GD::Graph::bars
RUN cpan PerlIO::gzip
RUN cpan LWP::Simple module

RUN pip install --upgrade pip
RUN pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose


